config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:index, :show] do

    post '/add_to_courses' => 'courses#add_to_courses'
    delete '/remove_from_courses' => 'courses#remove_from_courses'

    resources :chapters, only: [:index, :show] do
      resources :challenges, only: [:index, :show] do
        post 'check_validation' => 'challenges#check_validation'
        get 'hints/:hint_id' => "challenges#get_hint"
        get 'get_next_hint' => "challenges#get_next_hint"
      end
    end
  end

  get '/my_courses' => 'courses#user_courses'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  get '/profile' => 'profiles#show'
  get '/profile/edit' => 'profiles#edit'

  root "pages#home"

  get '/about-us' => 'pages#about_us'
  get '/restaurant_css_game' => 'pages#restaurant_css_game'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
    @courses = @user.courses
    @badges = @user.badges
    @other_courses = Course.where('id NOT IN (?)', @courses.map { |c| c.id })
  end

  def edit
    @user = current_user
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <%= render '/devise/registrations/edit_profile' %>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-sm-3">
      <%= gravatar_for(@user, { size: 200 }) %>
    </div>
    <div class="col-md-10 col-sm-9">
      <br>
      <h3><%= @user.name %></h3>
      <p><%= @user.username %></p>
      <p><%= @user.email %></p>
      <p>
        <%= link_to t('profile.edit'), profile_edit_path %>
        |
        <a href="#" data-toggle="modal" data-target="#edit_photo_modal">
          <%= t('profile.edit_photo') %>
        </a>

        <!-- Modal -->
        <div class="modal fade" id="edit_photo_modal" tabindex="-1" role="dialog" aria-labelledby="editPhotoModal" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="editPhotoModal"><%= t('profile.edit_photo') %></h4>
              </div>
              <div class="modal-body">
                <ol>
                  <li>
                    ادخل إلى الرابط التالي
                    <a href="https://ar.gravatar.com/">https://ar.gravatar.com</a>
                  </li>
                  <li>إذا لم يكن لديك حساب قم بانشاء حساب جديد.</li>
                  <li>قم بتسجيل الدخول.</li>
                  <li>ادخل إلى صفحة <a href="https://ar.gravatar.com/emails">إدارة الصورة الشخصية</a>.</li>
                  <li>قم بإضافة صورة جديدة.</li>
                  <li>اجعل هذه الصورة هي الصورة الخاصة بالبريد الإلكتروني الذي قمت التسجيل به في BitCode.</li>
                </ol>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal"><%= t('general.close') %></button>
              </div>
            </div>
          </div>
        </div>
      </p>
    </div>
  </div>
  <hr>
  <div class="user-badges">
    <h3><%= t('badges.my_badges') %></h3>
    <div class="row badges-list">
      <% @badges.each do |badge| %>
        <div class="col-md-3 col-sm-4 col-xs-12">
          <%= image_tag badge.picture, width: "100%" %>
          <p><%= badge.name %></p>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="user-courses">
    <h3><%= t('courses.my_courses') %></h3>
    <div class="row courses-list">
      <% @courses.each do |course| %>
        <%= render '/courses/course_block', course: course %>
      <% end %>
    </div>
  </div>
  <div class="other-courses">
    <h3><%= t('courses.other_courses') %></h3>
    <div class="row courses-list">
      <% @other_courses.each do |course| %>
        <%= render '/courses/course_block', course: course %>
      <% end %>
    </div>
  </div>
</div>