config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:index, :show] do

    post '/add_to_courses' => 'courses#add_to_courses'
    delete '/remove_from_courses' => 'courses#remove_from_courses'

    resources :chapters, only: [:index, :show] do
      resources :challenges, only: [:index, :show] do
        post 'check_validation' => 'challenges#check_validation'
        get 'hints/:hint_id' => "challenges#get_hint"
        get 'get_next_hint' => "challenges#get_next_hint"
      end
    end
  end

  get '/my_courses' => 'courses#user_courses'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  get '/profile' => 'profiles#show'
  get '/profile/edit' => 'profiles#edit'

  root "pages#home"

  get '/about-us' => 'pages#about_us'
  get '/restaurant_css_game' => 'pages#restaurant_css_game'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_attached_file :video

  # Validates
  validates :title, :presence => true
  validates :youtube_url, :presence => true

  # validates :video, :attachment_presence => true

  # validates_with AttachmentPresenceValidator, :attributes => :video

  # validates_attachment :video, :presence => true,
  #   :content_type => {
  #     :content_type => [
  #       "video/mp4",
  #       "video/ogg"
  #     ]
  #   }

  # Relations
  belongs_to :course
  has_many :challenges, :dependent => :destroy
  has_many :badges, :dependent => :destroy

  # RailsAdmin
  rails_admin do
    list do
      field :id
      field :title
      field :desc
      field :youtube_url
      field :course
    end
  end

  #frindly_id
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Methods
  def next
    Chapter.where('id > ?', self.id).order('id ASC').first
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
    authorize! :index, @chapters, :message => t("messages.you_are_not_authorized")
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    authorize! :show, @chapter, :message => t("messages.you_are_not_authorized_visitor")

  rescue CanCan::AccessDenied
    #redirect_to '/users/sign_in', :message => "test one"
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :desc, :video, :course_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/_index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 chapters_list">
    <% @chapters.each do |chapter| %>
      <div class="list-group">
        <%= link_to course_chapter_path(chapter.course, chapter), class: "list-group-item" do %>
          <h4 class="list-group-item-heading"><%= chapter.title %></h4>
          <p class="list-group-item-text"><%= chapter.desc %></p>
          <% if chapter.challenges.length > 0 %>
            <br>
          <% end %>
          <ul>
            <% chapter.challenges.each do |challeng| %>
              <li> <%= challeng.name %> </li>
            <% end  %>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<div class="container">
  <h1><%= t('chapters.list') %></h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Desc</th>
        <th>Video</th>
        <th>Course</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @chapters.each do |chapter| %>
        <tr>
          <td><%= chapter.title %></td>
          <td><%= chapter.desc %></td>
          <video width="320" height="240" controls>
            <source src="<%= chapter.video.url %>" type="video/mp4">
            <source src="<%= chapter.video.url %>" type="video/ogg">
            Your browser does not support the video tag.
          </video>
          <td><%= chapter.course_id %></td>
        <!--  <td><%= link_to 'show', course_chapter_path(chapter.course, chapter) %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<% meta title: @chapter.course.name + " - " + @chapter.title %>
<% meta description: @chapter.desc %>

<div class="container">
  <h1>
    <%= @chapter.title %>
    <small>
      <%= link_to t('challenges.see_challenges'), course_chapter_challenges_path(params[:course_id], params[:id]) %>
    </small>
  </h1>
  <p>
    <%= @chapter.desc %>
  </p>

  <div class="video-container">
    <iframe src="<%= @chapter.youtube_url %>?rel=0&amp;showinfo=0" frameborder="0"" style="width: 800px !important;height: 450px !important;">
    </iframe>
  </div>
</div>
<br>
<div class="video-challaneg text-center">
<%= button_to "إلى التحديات!", course_chapter_challenges_path(params[:course_id], params[:id]), :class => "btn btn-primary btn-lg", :method => :get  %>
</div>
<br>
<br>