config/routes.rb
Rails.application.routes.draw do

  resources :courses, only: [:index, :show] do

    post '/add_to_courses' => 'courses#add_to_courses'
    delete '/remove_from_courses' => 'courses#remove_from_courses'

    resources :chapters, only: [:index, :show] do
      resources :challenges, only: [:index, :show] do
        post 'check_validation' => 'challenges#check_validation'
        get 'hints/:hint_id' => "challenges#get_hint"
        get 'get_next_hint' => "challenges#get_next_hint"
      end
    end
  end

  get '/my_courses' => 'courses#user_courses'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  get '/profile' => 'profiles#show'
  get '/profile/edit' => 'profiles#edit'

  root "pages#home"

  get '/about-us' => 'pages#about_us'
  get '/restaurant_css_game' => 'pages#restaurant_css_game'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 links_footer">
        <ul>
         <li> <a href="http://bit-code.net/courses"><%= t 'courses.plural' %></a></li>
         <li> <a href="http://bit-code.net/about-us">عن الموقع</a></li>
         <li> <a href="http://bit-code.net/about-us#team">فريق العمل</a></li>
         <li> <a href="http://bit-code.tumblr.com/">المدونة</a></li>
         <li><%= link_to t('general.contact_us'), contact_us_path %></li>
       </ul>
      </div>

      <div class="col-md-6 social-footer">
        <h5>تابعنا على:</h5>
             <ul>
               <li> <a href="https://twitter.com/BitCodeAR"><%= image_tag "social-media-icon/tw.png", class: "sm-footer" %></a></li>
               <li> <a href="https://facebook.com/BitCodeAR"><%= image_tag "social-media-icon/fb.png", class: "sm-footer" %></a></li>
               <li> <a href="https://www.youtube.com/channel/UCe2UbCAARD1ftAIbSsVhaYg"><%= image_tag "social-media-icon/yt.png", class: "sm-footer" %></a></li>
             </ul>
      </div>
      <div class="col-md-4 info-footer">
          <p>
            في BitCode ستقوم بتعلم المهارات الأساسية التي تحتاجها لتنطلق في عالم تطوير الويب، بطريقة تفاعلية وباللغة العربية!
            <h6>Powered By:</h6>
          </p>
            <div class="info-footer-gp">
              <a href="http://www.gamepower7.com/"><%= image_tag "GP7.png", alt: "GamePower7" %></a>
            </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 footer-copy">
        <h6>جميع الحقوق محفوظة لـ BitCode &copy; 2015</h6>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_footercoloer.html.erb
<nav class="navbar navbar-default navbar-color">
  <div class="container">
    <%= form_for :challenges, remote:true, html: {id: "formcode2"}  do |f| %>
      <p>
        <%= hidden_field_tag :text  %>
      </p>
      <p>
        <%= f.submit "إرسال", class:"btn btn-primary btn-sm"%>
      </p>
    <% end %>

  </div>
</nav>

app/views/layouts/_head.html.erb
<meta charset="UTF-8">
<% metamagic site: "BitCode", title: [:site, :title], separator: " — " %>
<%= metamagic %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel=”publisher” href=”https://plus.google.com/+BitcodeNetAR”/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:type" content="website" />
<meta property="og:locale" content="ar_AR" />
<meta property="og:locale:alternate" content="en_US" />
<meta property="og:site_name" content="BitCode"/>

<% meta og: {image: "http://bit-code.net/image.png"} %>
<% meta twitter: {card: "summary",  site: "@BitCodeAR"} %>

<meta name="author" content="" />
<meta name="robots" content="all" />
<meta name="google-site-verification" content="yUFtA4-JHRIzvwdHHL2-TAi4-Lk3Zy7HvioQ7vTEbOY" />

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= favicon_link_tag 'favicon.ico' %>


<%= if content_for?(:head_tags)
  yield(:head_tags)
end %>
<%= csrf_meta_tags %>

<% if alert && !alert.empty? %>
  <script>
    $(document).ready(function (argument) {
      showNotify("", "<%= alert %>", "error");
    });
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default <%= request.path != '/' ? 'navbar-color' : '' %>">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), root_path, :class => "navbar-brand"%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('courses.my_courses'), my_courses_path %> </li>
              <!-- <li><%#= link_to t('acount.settings'), root_path %> </li> -->
              <li><%= link_to t('acount.my_profile'), profile_path %> </li>
              <li><%= link_to t('acount.sign_out'), destroy_user_session_path, method: :delete %> </li>
            </ul>
          </li>
          <li class="navbar-text"><%= current_user.score.to_i %> نقطة </li>
        <% else %>
          <li>
            <%= link_to t('acount.sign_up'), new_registration_path(resource_name), class: "signup-navbar" %>
          </li>
          <li>
            <%= link_to t('acount.sign_in'), new_session_path(resource_name) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbarcolor.html.erb
<nav class="navbar navbar-default navbar-color">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("bitcode-long-logo.png"), root_path, :class => "navbar-brand navbar-brand-color"%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t('courses.my_courses'), root_path %> </li>
              <li><%= link_to t('acount.settings'), root_path %> </li>
              <li><%= link_to t('acount.sign_out'), destroy_user_session_path(resource_name), method: :delete %> </li>
            </ul>
          </li>
          <li class="navbar-text"><%= current_user.score.to_i %> نقطة </li>
        <% else %>
          <li>
            <%= link_to t('acount.sign_up'), new_registration_path(resource_name), class: "signup-navbar" %>
          </li>
          <li>
            <%= link_to t('acount.sign_in'), new_session_path(resource_name) %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">اسم الدورة<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li> <a href="#">اسم الشابتير</a></li>
                <ul class="dropdown2">
                  <li><a href="#"> التحدي الأول</a></li>
                  <li><a href="#"> التحدي الأول</a></li>
                  <li><a href="#"> التحدي الأول</a></li>
                  <li><a href="#"> التحدي الأول</a></li>
                  <li><a href="#"> التحدي الأول</a></li>
                  <li><a href="#"> التحدي الأول</a></li>
                </ul>
          </ul>
          </li>
      </ul>

    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="ar" lang="ar">
<head>
  <%= render 'layouts/head' %>
</head>
<body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-62427306-1', 'auto');
      ga('send', 'pageview');
    </script>
</body>
</html>